### ISSUE TITLE
F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [thermatk/FastHub-Libre#1]
Is this viable? 

Ref: https://gitlab.com/fdroid/fdroiddata/issues/748

**Comment by thermatk** [comment]
I can't guarantee I don't lose interest in endless rebasing and cutting-out of bleeding edge proprietary "functionality" from upstream
For now, 3.0.0 is liberated

OctoDroid which merged my PRs is liberated and after next release I'll re-publish it on F-Droid:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2269

**Comment by ildar** [comment]
Thanks a lot! Anyway. Really, I mean it. Your effort is hard to
overestimate.
Liberating apps is very, very important. And I think at some point it's
worth getting back to upstream and ask them to support the branch. Maybe
they can find some motivation to carry on.

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by k0shk0sh** [comment]
@ildar well I could possibly do that, however @thermatk didn't respect that it was hard decision for me to decide that and satisfy everyone, he knows how hard it is to keep two copies of each new thing we want to add that uses the Google play service,  he knows that we needed to fix a bug in two places instead of one, I actually branched out foss branch so we could maybe provide support from there, but Ruslan, never thought of speaking to me privately like I did when I decided to drop it. 
Anyway I'm not against all of that in fact I do support this whole idea and proved that by putting this repo in fasthub readme, @thermatk you still know where you can find me, hit me up if you wanna talk about all of this privately. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thermatk** [comment]
@k0shk0sh 
it's not like you didn't delete and lock harmless comments upstream and decided to drop the code with some sort of a Soviet press release about a "unanimous decision", without ever ever mentioning me on github or slack(a simple @thermatk results in an email message on both services!), even though when I tried to find what I probably missed on Slack... there was nothing, there was no discussion, at least search didn't show anything. I was ready to maintain that code, I was ready to help when it broke, when one puts time in a project one would expect at least a mention.

I don't understand this and I hope I just didn't get something, gmail had an outage or whatever, but that was managed poorly and I'm angry, which leads me to the POV I can only fork and see upstream as unfriendly :rofl: 

Please don't start this pushing blame around, code is GPLv3, this is a fork

**Comment by k0shk0sh** [comment]
@thermatk no one here to blame but me ;) . Good luck 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@thermatk I want to apologize.
@k0shk0sh may be upset that I am writing this but it has bothered me since day one.

The decision to drop F-droid IMHO was not a very thought out one. It came about when someone got very frustrated with some of the issues the F-droid was causing.

The person did *not* know (nor did I) that you had spent an enormous amount of time and effort getting F-droid to work. This includes add/changing the libraries, getting the app approved and maintaining it too.

At the same time @k0shk0sh was busy with some personal stuff and when this came about I don't believe there was much thought put into it.
For this reason I feel that you are due an apology, plus a tremendous thank you for the work you have put in.

I was asked before they dropped support and just to show you that I was unsure of your work I am including a picture of what I responded.

![image](https://user-images.githubusercontent.com/16872793/27013531-b7ec6e84-4eb3-11e7-83cf-b22f779c6564.png)

Had I known the amount of work you had put in I would have let you know about it. But I did not know.

Therefore I offer a sincere apology

PS:
There is one thing that I would like you to understand.
I do defend @k0shk0sh for locking the thread. At that time there was a lot of anger and I feel too the best thing was to lock the thread.
I hope you understand and forgive us (at least me) for what happened.

**Comment by IzzySoft** [comment]
There was [a new request filed at F-Droid to include FastHub-Libre](https://gitlab.com/fdroid/rfp/issues/281) with the official repo. However, that would mean the two apps clashing. Wouldn't it be a good idea to use a different package name – e.g. `com.fastaccess.github.libre` – to distinguish the two while still showing its "ancestry"?

**Comment by rugk** [comment]
Now [two](https://gitlab.com/fdroid/fdroiddata/issues/748) [issues](https://gitlab.com/fdroid/rfp/issues/281) on F-Droid's side are open (and I don't understand why or what is the difference)…

In any case in the [one issue](https://gitlab.com/fdroid/fdroiddata/issues/748) someone requiested the same:
> If this fork changes package ID it can be submitted as a new app. See the Inclusion Policy.

**Comment by thermatk** [comment]
@yakov116 thank you for your kind words 👍 
@IzzySoft @rugk I'll update package name when I update, which is when Android Studio becomes stable. That's what I'm waiting for this whole time 😃

**Comment by rugk** [comment]
So how is the current state? I still could not find FastHub-Libre on F-Droid…

**Comment by IzzySoft** [comment]
@rugk Check the [issue on RFP](https://gitlab.com/fdroid/rfp/issues/281). Rebranding was mentioned there yesterday, and @thermatk made a [MR on fdroiddata](https://gitlab.com/fdroid/fdroiddata/merge_requests/2614). If the latter gets accepted and the build succeeds, it shouldn't be much more than a few days for the app to turn up there.

**Comment by BrainBlasted** [comment]
Merged :D

**Comment by licaon-kter** [comment]
It's not done yet, keep an eye on the builds page: https://f-droid.org/wiki/page/com.fastaccess.github.libre

**Comment by rancidfrog** [comment]
There is a bug trying to create new issue:
![](https://i.imgur.com/uQvUbwB.png)
It says a new version is available and takes you to: https://play.google.com/store/apps/details?id=com.fastaccess.github.libre
Which does not exist.

Also, I noticed that there is no apk in release section for latest build.
Is that due to fdroid?
Can apk still be added to release section for those who prefer it or debugging, as fdroid is mostly delayed

**Comment by thermatk** [comment]
@rancidfrog
Really, but this only affects this repo. Will probably have to kill this versioncheck altogether, thanks
The problem with me publishing release apks is that I'll sign them with my keys, while fdroid signs with its own, which adds to confusion

**Comment by IzzySoft** [comment]
That signature issue will always exist if you have your app on F-droid *and anywhere else* (until F-Droid supports dual signing, which AFAIR is on its todo list). So this makes the question: Do you want you app to be F-Droid only (and live with the delay) – or simply point out the signature issue to unawares, and attach the APK anyway?

**Comment by rancidfrog** [comment]
You can do what newpipe, https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.10.2, does:
![](https://i.imgur.com/RN292BA.png)

**Comment by ildar** [comment]
... or upload F-Droid apk to github releases, though that'll leave the core
problem of delay. Though @thermatk planned rare releases anyway 😛

**Comment by IzzySoft** [comment]
@ildar that would be putting the cart in front of the horse. Idea of the APK being attached here was to have it *earlier* (ie. to avoid the delay) :wink:
