### ISSUE TITLE
PRO FEATURES

### ISSUE THREAD

**Issue by k0shk0sh** [thermatk/FastHub-Libre#6]
Hey buddy, thanks for the continuous work on this fork. 

I have noticed that you enabled all FastHub PRO FEATURES for FREEEEE which I respect that you didn't consider making money out of it, however I have included awhile ago that no FORK should enable or use these features as its something i'm making living out of it and by you making it free for all from different website will definitely hurt me and the buyers who bought these features from the Playstore. 

So, could you please remove all of these features from your fork?

**Comment by ildar** [comment]
@k0shk0sh , excuse me for breaking into it.
Do you have a gradle switch for the features? How do you turn them on and
off?

**Comment by k0shk0sh** [comment]
They are handled within the app source code, no gradle involved into this. He knows where these stuff to be turned off or removed completely as he actually removed the checks for them to be enabled/disabled and they are now always enabled.

**Comment by thermatk** [comment]
Hi @k0shk0sh, 
This is a fork for my personal usage and, as a side effect, for people you abandoned that have no Play Services or Play Store, so the userbase is different and it is highly unlikely to hurt any of your sales. I've stumbled upon all the switches for some features while removing endless "isgoogleplay"-this-and-that and decided to go the easiest route - delete all checks & enable everything until it compiles.
I will kindly reject your request for now

**Comment by k0shk0sh** [comment]
You should have deleted the code to it as well instead of just removing the checks. 

I'm trying to be as nice as I can, and gonna ask again, would you please remove the pro features out of your fork? I could help you with that if your excuse is just to make everything work.
Let me know and i'll make a PR right away.

**Comment by thermatk** [comment]
@k0shk0sh no, let me make a stand here. I don't really need an argument here, but I would change the AppName if you'd be happier :) 

If you want to get into a discussion:
1. Me or whoever else can't buy these things or even activate them, if already previously bought, on a gapps-free device. 
2. What if I would want to make money of some features as well? You really think that would be a disrespectable thing to do? 😈

**Comment by k0shk0sh** [comment]
Well basically you are right and if this is how you think of open source then I also can make sure this repo to be shut down and also in foss, but I don't wanna go into this because I know you aren't that kinda of person. 



I'm making the changes right now and gonna submit a pr soon ;) .

**Comment by thermatk** [comment]
@k0shk0sh I'm seriously doubting what you've said now
The whole of code is under GPL, so please get out of my repo. 
I'm not distributing binaries hiding sources for them, I'm exactly doing what the license requires me to do - sharing the sources of modifications.
I can sell your app on Google Play in 25 different flavours for 100$ each.
I'm honestly not behaving nice here, but don't threaten me

**Comment by k0shk0sh** [comment]
Well, I guess you have missed reading the license then, before you fork  latest changes, have you checked the license file of FastHub? Have you read it? Nope. 

I'm not threaten you, I came to you nicely and asked you gently you are who takes things way to serious. 


So again, Ruslan, should I proceed with my PR?

**Comment by thermatk** [comment]
@k0shk0sh of course I read the GPL v3.0
Now I have some legal advice for you:

1. Please update the README and badge of your repo that your license is not GPLv3
2. Also, don't forget to exclude Section 7 from your modified license, which shouldn't be called GPL anymore, because it explicitly kills your additional terms.
3. Actually, correct me if I'm wrong, but you had no legal right to change the license on the 3rd of September out of the blue, without getting consent from all people who have ever contributed to your repo. I don't remember any letters asking my permission, for instance.
4. The only nice way you could do that was not to invent a k0shGPL but just have your very cool features properly modularised, shared in another repo or not shared at all and properly connected with the GPL source of the app during build time(respecting all applying rules and licensing the connecting interfaces with a less strict license than GPL) or maybe make a separate APK and sell it separately, I don't really know the best way.

I do this for educational purposes here and I hope that you too, because this can't be a conversation about color codes, can it?

**Comment by thermatk** [comment]
Update: point 3 is valid, I'm not wrong. I've sent a friendly PR to protect you from legal trouble: https://github.com/k0shk0sh/FastHub/pull/1190

**Comment by thermatk** [comment]
I've looked into the code and features in detail and I think it's ok to remove unlocked themes(haven't found the nicest way or key yet), but not features. Probably remove the themes from interface or replace with a nice reminder that users might donate to developers?
I wouldn't want to make this fork an example of crippleware though, especially because me or some other users probably don't even have the possibility to unlock features for money. Judging from comments about disrespecting those that dislike Google's binaries, you don't really care about us, but let me at least remind you about the existence of Chinese guys or Amazon Fire OS users, who don't even have a choice to _use gms_ 👍 
What do you say @k0shk0sh?

**Comment by k0shk0sh** [comment]
Still, I think the pro features shouldn't be shipped, I think it will be fair for everyone, themes ain't what people buy, but pro & enterprise and that's my concern. 
I'm still thinking of a way to satisfy everyone but first will be my paid users. 

What do you think?

**Comment by yakov116** [comment]
@thermatk I want to apologize for what I have said yesterday. There was no need for my comment and I take back the unnecessary bashing.

But I think you agree to some point that the way you handled this was not the correct way too.

I'm sorry and I hope you will move forward with this in the correct way.

**Comment by thermatk** [comment]
![screenshot_1509272292](https://user-images.githubusercontent.com/2287483/32143329-b40136e2-bcb8-11e7-8655-9d51f5ccfcc5.png)
![screenshot_1509272296](https://user-images.githubusercontent.com/2287483/32143330-b423964c-bcb8-11e7-9884-53bf499ded92.png)
how about that?

**Comment by k0shk0sh** [comment]
@thermatk is not about the money really, I do give people free promo code that unlocks everything basically for free. 

Its about those who wrote medium articles about FastHub and the students that sent me their ids to get free promo codes, now basically everyone will ignore that and go get it from foss because they know that there is a kinda of pirated version of FastHub that give you everything for free without any restriction. 


I really don't know what do in here, I gave my opinion and as a forke that didn't violate anything, I think its your decision to make, either be the guy who pirate it or be the guy didn't.

Its really up to you now. 

```
No insult intended!
```

**Comment by dimqua** [comment]
@k0shk0sh are you afraid that existence of this fork may negatively affect FastHub popularity?

**Comment by k0shk0sh** [comment]
@dimqua no, not really, FastHub is brand.

**Comment by LivInTheLookingGlass** [comment]
Its not pirating. You licensed it openly. Even if someone didn't use this fork, it wouldn't be too hard for them to make their own.

Near as I can tell you've been consistently rude about this fork, even before this issue. I think that I would struggle to be polite about this, especially since you seem to realize you're doing it.

**Comment by yakov116** [comment]
@gappleto97 I have a serious question for you, I am not trying to attack you in any way,

How would you feel if someone (even legitimately) took your work that you are making money from and started giving it out for free?

**Comment by BrainBlasted** [comment]
@yakov116 That's part of the risk one takes when licensing software 
under the GPL. Most software companies selling GPL software actually 
sell support contracts. The nature of the GPL makes it so that forks 
can be made when the community sees the need to branch off, and anyone 
can distribute the source code.  Since you included all pro features in 
the FastHub repository, there is no restriction under the GPL on who 
can fork it and how.

As of now, if you'd want to prevent this in the future, you would need 
express permission from all past contributors to re-license the 
software and introduce a CLA.

**Comment by k0shk0sh** [comment]
@gappleto97 not everything I wrote has to be rude, its just how you read it, and I think I cleared this with Ruslan that there is no threatening nor rudeness in my comments, we are discussing different ways of tackling this and everyone is free to speak their mind and everyone else free to understand them the way they like. For example: you got them as I'm being impolite where I'm not in my way of reading back my comments.

**Comment by yakov116** [comment]
@BrainBlasted You missed the point I was trying to bring out.

>Near as I can tell you've been consistently rude about this fork, even before this issue. I think that I would struggle to be polite about this, especially since you seem to realize you're doing it.

I was responding to his accusations. That even if it is legitimate give the guy some way to express himself and don't look for the bad in every little bit.

>That's part of the risk one takes when licensing software
under the GPL. Most **software companies** selling GPL software aactually
sell support contracts

Here is a major point. @k0shk0sh is not a **software company** and is not trying to be like one. Just like you understand that he made this open source for all to enjoy. So too there is an *unspoken* rule when it comes to open source.
That *"rule"* is that the DEV deserves some respect.

He said the he worked hard and has asked that the pro item not be distributed. IMHO (I think @k0shk0sh would agree) that there would be no issue to make a "Non-Google" version **including** the pro item. As long as it was not compiled. This would make you standard guy off the street go to the original dev and pay for his hard work.
Even @k0shk0sh gives them free if you compile it alone.

**Comment by BrainBlasted** [comment]
The software company bit was for a point of reference as to why it is 
difficult to make a profit off of selling FOSS software. Due to the 
nature of the GPL, I don't believe you can prevent someone from 
distributing a fork or binaries.

Also, not to be rude, but what's the use if compiling it yourself 
already gives you pro features? This version is intended for people 
unable to use Google Play Services, like those running LineageOS or 
those in China.

**Comment by thermatk** [comment]
The fears are exaggerated, the people who use apps from F-Droid either won't buy anyway and/or, sadly, are technically skilled to compile :smile:

**Comment by yakov116** [comment]
>The software company bit was for a point of reference as to why it is
difficult to make a profit off of selling FOSS software.

But you obviously are using that to show your point. 

@thermatk LOL
Its true but I think the point still exists.

**Comment by k0shk0sh** [comment]
@thermatk, go ahead, distribute as it is for now, until later if anything change I'll make a PR for it and we discuss it privately.

For the meantime, lets close this page and open new one.

Also, please lock comments on this issue for the sake of future.

**Comment by k0shk0sh** [comment]
So pathetic and dramatic to read the readme.


Well played.

**Comment by thermatk** [comment]
FastHub developers, please
In your own words, "get a life"! Stop following every little change here 😄
Try to be professional and stop dramatically accusing me of being dramatic(like it's a bad thing, after all).
As for the readme, everything I wrote can be justified with links, but why would we need to go there? And i don't know who you take it personal, I've never mentioned names. @k0shk0sh please relax, most of the things you're probably angry about have been written by your collaborators, not you. Yet people with write access, collaborators exercising power, are representatives of the upstream project, so their public opinion justified with actions is the project's opinion.
I've written an explanation as to why these changes are not upstream, because otherwise why would I fork? 
What exactly do you want to change? 

In the pro features, as far as i can see, we came to a stale:
- You believe I should care about your users being offended by the idea that features can be used for free, although it wouldn't actually really hurt sales because F-Droid is a small and independent market with a different target audience. So, it's a principle you try to force
- I believe I should care about myself and my potential users and don't see a reason why I should turn the app into a crippled thing. There never was a solution, an alternative promocode or check proposed. My position is based on a principle as well

The thing that people's feelings get hurt so easily these days should be of utmost interest for social sciences

**Comment by yakov116** [comment]
>I've never mentioned names. 

Nothing to with him. **I am personally hurt.** Do it for my sake.
I think that  I am not so biased as you can see from here https://github.com/thermatk/FastHub-Libre/issues/1#issuecomment-307648463 

>because otherwise why would I fork?

Is there a need to explain?

>I believe I should care about myself and my potential users and don't see a reason why I should turn the app into a crippled thing. There never was a solution, an alternative promocode or check proposed. My position is based on a principle as well

A serious question, is there a real option?

**Comment by thermatk** [comment]
@yakov116 please be more specific, also the PR from k0shk0sh is somehow merged

**Comment by yakov116** [comment]
>PR from k0shk0sh is somehow merged

?
>please be more specific

This part

>Ideological reasons
Upstream developers get offended by the high standards of the F-Droid community, which inevitably result in an Anti-Feature: Non-Free Network badge for any Github client
Upstream developers mistreat all users of Android devices without GMS for either being unlucky or even wrong in beliefs, so while an apk is provided for download outside of Google Play, the simplest effort to add an else clause and reimplement some features without using Google's push mechanism is never done and won't be accepted
Upstream app has some so-called PRO-features, some of them quite useful, lack of which turns the software into crippleware. Despite continous requests through different channels by various users, even having quite a multitude of checks for existence of various parts of the Google Play Services, these checks once again don't have an else clause, so even when the app knows that there is no possible way to unlock these features by payment it just goes back a page with an error
There are some promocodes distributed either to students who need to send their personal documents to the developer(what and how particularly is checked is unknown, privacy implications are unknown) or non-students who have to write articles praising the app. Funnily, the promocodes can only be entered by those who use GMS, as once again the method fails on the first line if (!isGoogleSupported()) return, which in this case can't be easily fixed because the codes are stored in a Firebase DB
Upstream developers have shown in the past that they lack a general understanding of the GPL principles or respect for them, misunderstanding whatever contradicts their beliefs or previous plans for an open-source abuse, piracy, etc.
Upstream developers strongly disapprove that in this fork one can access the so-called PRO features without paying
This fork will have to carry on without approval until a better solution to please upstream will surface
I've made the unlocking page and the way to this page as respective and nudging to go and support as I could

**Comment by BrainBlasted** [comment]
I've made some changes to that part in #9
